name: Update README with Repo List

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:     # allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Fetch public repos and update README
      run: |
        #!/bin/bash

        GH_USER="mauriziosessa"
        LIST=$(curl -s "https://api.github.com/users/$GH_USER/repos?per_page=100" | jq -r '.[] | "- [\(.name)](\(.html_url))"')

        sed -i '/<!-- REPO_LIST_START -->/,/<!-- REPO_LIST_END -->/c\
<!-- REPO_LIST_START -->\n'"$LIST"$'\n<!-- REPO_LIST_END -->' README.md

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update repo list" || echo "No changes to commit"
        git push
